version: '3'

services:
  huutokauppa_ebay:
    build: .
    container_name: huutokauppa_ebay
    ports:
      - 8001:8001
    environment:
      PYTHONBUFFERED: 'true'
    depends_on:
      - huutokauppa_postgres

  huutokauppa_celery:
    build: .
    container_name: huutokauppa_celery
    command: celery worker -l info -A application
    depends_on:
      - huutokauppa_postgres
      - huutokauppa_redis

  huutokauppa_redis:
    image: redis
    container_name: huutokauppa_redis
    volumes:
      - 'redis:/data'
  
  huutokauppa_postgres:
    image: postgres
    container_name: huutokauppa_postgres
    environment:
      - POSTGRES_PASSWORD=huutokauppapassword
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
      
volumes:
  redis:
